# Generated by Django 4.2.7 on 2023-12-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is_pleasant_habit')),
                ('frequency', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Frequency (days)')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reward')),
                ('time_to_completed', models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='Time_to_completed(seconds)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is_public')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Associated_habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
